development:
  sessions:
    default:
      database: bucketline_development
      hosts:
        - localhost:27017
      options:

test:
  sessions:
    default:
      database: bucketline_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
        identity_map_enabled: true

production:   
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
        identity_map_enabled: true

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
        identity_map_enabled: true
